# Site settings
title: Midnight Oil Refinery
email: andrew@andrewcull.io
description: > # this means to ignore newlines until "baseurl:"
  We are a collective of designers and developers who create elegant and beautiful content-centered, conversion-focused web design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://midnightoilrefinery.com" # the base hostname & protocol for your site
twitter_username: andrewcullio
github_username:  midoil

# Build settings
markdown: kramdown

# Prose.io Settings
prose:
  siteurl: "http://midnightoilrefinery.com"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Write your awesome title here!"
      - name: "categories"
        field:
          label:"Categories"
          element: "text"
          value: "enter categories, separate with comma"
