# Site settings
title: Midnight Oil Refinery
email: andrew@andrewcull.io
description:
  We are a collective of designers and developers who create elegant and beautiful content-centered, conversion-focused web design.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /articles/:title
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: andrewcullio
github_username:  midoil

# Build settings
markdown: kramdown

prose:
#  rooturl: '_posts'
  siteurl: 'http://prose.github.io/starter/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Add Tags"


# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
